### PR TITLE
feat: Settings page

### PR DESCRIPTION
**Pull request by 0neGal**
In short this is to make it easy for the user to edit Viper's settings file graphically, but also to edit Northstar arguments and any other settings we may add in the future.

##### TODO

 - [x] UI
   - I may do small tweaks before merge... 
 - [x] Localization
   - [x] French (`fr.json`)
   - [x] Spanish (`es.json`)
 - [x] Functionality
   - [x] Changing `viper.json` settings
   - [x] Changing NS launch arguments
<details>
    <summary>Current iteration of the UI:</summary>

</details>

### CODE REVIEW

**Comment by 0neGal** [comment]
@Alystrasz how do we check if Viper is running in a version that can auto-update or not? I just came across an issue, since we check for Northstar updates after `electron-updater` reports no update is available, it'll never check for Northstar updates if it's running as a version that doesn't have auto-update capabilities, as that events (`update-not-available`) never runs.

Hence we need to check if the user is in a version that can auto-update, and if not, simply run the Northstar updater. Or well, preferably the updated code that allows the user to disable Northstar auto-updates:

```js
if (settings.nsupdate || cli.hasArgs()) {
	handleNorthstarUpdating();
}
```

Besides this we also need it so we can hide the **"Viper Auto-Updates"** options in settings, as it has no purpose if it can't auto-update. As always, I've not clue how `electron-updater` really functions, which is why I'm asking for help :p

**Comment by Alystrasz** [comment]
Checking the `autoUpdater` documentation, I found this: `isUpdaterActive(): boolean;`
So `autoUpdater.isUpdaterActive()` should do the job!

**Comment by 0neGal** [comment]
> Checking the `AppUpdater` documentation, I found this: `isUpdaterActive(): boolean;` So `autoUpdater.isUpdaterActive()` should do the job!

This worked flawlessly, I don't know how I missed trying to read the documentation :p

<br><br>

Besides some additional testing on Windows, if possible, everything should be in order functionally, and likely UI wise... I localized all the strings into English, and so they need to be localized into the various languages (@Alystrasz, @AA-Delta)

```json
"gui.settings.save": "Save",
"gui.settings.discard": "Discard",
"gui.settings.title.ns": "Northstar",
"gui.settings.title.updates": "Updates",
"gui.settings.nsargs.title": "Launch options",
"gui.settings.nsargs.desc": "Here you can add launch options for Northstar/Titanfall.",
"gui.settings.autoupdate.title": "Viper Auto-Updates",
"gui.settings.autoupdate.desc": "Viper will automatically keep itself up-to-date.",
"gui.settings.nsupdate.title": "Northstar Auto-Updates",
"gui.settings.nsupdate.desc": "Viper will automatically keep Northstar up-to-date, however it can still manually be updated through the Northstar page.",
"gui.settings.excludes.title": "Retain files on update",
"gui.settings.excludes.desc": "When Northstar is updated, files specified here will not be overwritten by files from the new Northstar update, unless you know what you're changing, you should probably not change anything here. Each file is separated with a space.",
```

Then I'll get a release ready with all the new features, if no issues are found of course!

**Comment by Alystrasz** [comment]
Since we have a dedicated view for settings, I suggest moving the "change gamepath" in it, and replacing the option with a "Settings" link.

**Comment by 0neGal** [comment]
> I suggest moving the "change gamepath" option in it, and replacing the option with a "Settings" link.

I considered it as well, but in the end I felt the old/current layout was still better, not to mention everything in the settings page currently is something you can edit, contrary to a button that changes right afterwards compared to after you click the **"Save"** button.

**Comment by Alystrasz** [comment]
> contrary to a button that changes right afterwards compared to after you click the "Save" button.

I don't see difficulty in implementing this, this is a pretty standard way to do it?

Capture d’écran 2022-02-24 213432

**Comment by 0neGal** [comment]
> I don't see difficulty in implementing this, this is a pretty standard way to do it?

It's not that it's difficult, it's moreso that I think it doesn't fit in, and the current version fits better. And again, mixing save/discard functionality and instant save when going through the dialog doesn't seem like the best idea, and making it work with the save/discard functionality would require redoing the whole gamepath selector code.

Not that, that is difficult, but, given I still don't think it fits better in the settings page compared to it's current location, I don't see reason in spending time on redoing it.

**Comment by Alystrasz** [comment]
This game path option on welcome page is not that intuitive for everybody it seems :)

**Comment by 0neGal** [comment]
I'm not quite sure how putting the button inside a settings page will be easier to explain than having it on the first page. 

> Click the "Change Game Path" button on the Welcome page

Compared to:

> Click the settings button in the top right corner, scroll down and click the "Change Game Path" button

The point I'm trying to make here is that it doesn't provide anything over having it on the welcome page. It's something that can be considered at a later stage, whether to put it both places or something similar, but as of right now, I still think the current placement is just fine.

I also wanna remind you the French localization is still missing, I'm not sure if you noticed my message earlier about it, or whether you were waiting to see if more string would be added. As soon as this is merged a new release will be made, and given I don't think the position of the button should change, it is really just the French localization holding up the release.

**Pull request merged**
