### PR TITLE
Mod support

### PR DESCRIPTION
**Pull request by 0neGal**
#### TODO

- [x] Managing Mods
  - [x] Removing
  - [x] Toggling
  - [x] Installing
    - [x] Folder Support
    - [x] Archive/Zip Support
    - Choosing between folders and archives
      - Due to how Windows and Linux works a file dialog can only select either folders or files, not both.
      - We'll handle this when the new UI is released instead of in the old UI
- [x] Translations (@Alystrasz)
- [x] Disable if NS isn't installed
  - [x] Backend
  - [x] Frontend
- [x] CLI Arguments

### CODE REVIEW

**Comment by Alystrasz** [comment]
Seems like you forgot to create a folder.

Capture d’écran 2022-01-03 110911

**Comment by 0neGal** [comment]
Out of curiosity does this folder have NS installed already? As that folder does get created...

```js
if (! fs.existsSync(disabled)) {
    fs.mkdirSync(disabled)
}
```

If it doesn't have NS installed I see why that error probably happened, I'll add some checks...

**Comment by Alystrasz** [comment]
Yup, NS is installed, but the `mods` folder is not created.

Error actually occurs l.201 of `utils.js`:
```javascript
let disabledPath = path.join(modpath, "disabled")
files = fs.readdirSync(disabledPath)
```
In `list` method, you do not check if `disabledPath` exists before reading it.

**Comment by 0neGal** [comment]
Should be fixed now, I assume it occurred because I added that code after I created the folder initially :p...

**Comment by Alystrasz** [comment]
Adding missing french translations in #30.
Sorry for the delay, I thought you wanted to complete missing tasks before merging this :)

**Comment by 0neGal** [comment]
I added a few new translations for the CLI options, after those are translated I'll merge this... 

missing translations: `cli.help.installmod`, `cli.help.removemod`, `cli.help.togglemod`, `cli.mods.failed`, `cli.mods.removed`, `cli.mods.toggled`, `cli.mods.installed`, `cli.mods.cantfind`, `cli.mods.toggledall`, `general.notinstalled`

**Pull request merged**
