### PR TITLE
feat: Support EA Desktop better

### LINKED ISSUE #182: EA-APP auto-quit
Include in the Setting "Automatically quit Origin", that it also closes the EA-App

### PR DESCRIPTION
**Pull request by 0neGal**
This should make support for the EA Desktop App much better, as it now is also closed alongside Viper if the setting for it is enabled.

This however does mean the old localization strings aren't very accurate anymore, as they don't make any mention of the EA Desktop App, and so new strings are needed.

Closes #182

#### Changed localization strings

From:

```json
"gui.settings.originkill.title": "Automatically quit Origin",
"gui.settings.originkill.desc": "When Viper exits, automatically quit Origin as well.",
```

To:

```json
"gui.settings.originkill.title": "Automatically quit Origin and or EA Desktop",
"gui.settings.originkill.desc": "When Viper exits, automatically quit Origin and or EA Desktop as well.",
```

#### Languages

 - [x] German - @DxsSucuk
 - [x] French - @Alystrasz
 - [x] Spanish - @AA-Delta

### CODE REVIEW

**Comment by DxsSucuk** [comment]
Instead of writing and or EA Desktop wouldn't it be better to use 
> Automatically quit Origin/EA Desktop

**Comment by 0neGal** [comment]
> Instead of writing and or EA Desktop wouldn't it be better to use
> 
> > Automatically quit Origin/EA Desktop

Not exactly, **"Origin/EA Desktop"** mostly implies **"Origin or EA Desktop"**, when it is in fact one or both. If you've Origin and EA Desktop open, both will be closed, if just one of them, then it's just that one.

Either way, it's mostly just for clarification :p

**Comment by DxsSucuk** [comment]
But EA Desktop does not allow Origins to be open? Doesn't it automaticly close Origins once you open it?

**Comment by 0neGal** [comment]
> Doesn't it automaticly close Origins once you open it?

I actually don't know, I don't have a Windows install available right now, and have yet to actually ever use the new EA Desktop App... :p

**Comment by DxsSucuk** [comment]
Well I am just talking out of memory but I remember EA Desktop showing a message "Closing Origins" when booting it up on the splash screen of it.

**Pull request merged**
