### PR TITLE
Add spanish translation

### PR DESCRIPTION
**Pull request by AA-Delta**
Add spanish translation (Latin-america) es.json

### CODE REVIEW

**Comment by AA-Delta** [comment]
Everything seem to look allright in respect to the locale

image

#44 here's a preview of the logo implemented in the launcher too

**Comment by 0neGal** [comment]
I assume this doesn't incorporate #53 yet (I don't expect it to), but more importantly, would you be against becoming the maintainer of the Spanish translation, meaning I'll @ you when more translations are required.

**Comment by AA-Delta** [comment]
> I assume this doesn't incorporate #53 yet

No, it's just the locale translation
>would you be against becoming the maintainer of the Spanish translation, meaning I'll @ you when more translations are required.

I would love to help! Count me in!

**Comment by 0neGal** [comment]
> I would love to help! Count me in!

Im planning on adding a section of the locale files that'll contain maintainer info, i.e:

```json
{
    "maintainers": [
        "https://github.com/<username>",
    ],

    ...
}
```

Containing some kind of contact links, preferably GitHub @

**Comment by AA-Delta** [comment]
>Quite possibly just having a maintainers.json file in src/lang/ would be better, as you can then have all maintainers in one file. Like so:

Sure, seems like it would be more convenient in one single file, and you could use it to show the maintainers on the GUI if needed for issues and corrections. I have all notifications on this repo, so I'll be updating the localization as soon as it's needed

**Comment by 0neGal** [comment]
> Sure, seems like it would be more convenient in one single file, and you could use it to show the maintainers on the GUI if needed for issues and corrections. I have all notifications on this repo, so I'll be updating the localization as soon as it's needed

When this is added, I'll be updating `build/langs.js`/`npm run langs` to also include who maintains each language when localizations are missing. Since we can just include that with this file automatically :)

**Comment by 0neGal** [comment]
Since #53 is now merged, that also means `gui.setpath` and `general.missingpath` need to be updated to reflect the change in wording... After this I'll merge this...

**Comment by AA-Delta** [comment]
> Since #53 is now merged, that also means `gui.setpath` and `general.missingpath` need to be updated to reflect the change in wording... Then I'll merge this...

Commit is done!

**Comment by 0neGal** [comment]
Lovely!

I'll be merging this then, I also added you into the `maintainers.json` file for the Spanish locale. Feel free to ever open a PR if you wish to no longer be in it!

**Comment by AA-Delta** [comment]
> Lovely!
> 
> I'll be merging this then, I also added you into the `maintainers.json` file for the Spanish locale. Feel free to ever open a PR if you wish to no longer be in it!

Don't worry, I hope i can help with everything I can for the longest time possible. Please if you see something wrong in my commits/branches/contributions,  don't hesitate to contact me, I literally learned to use GitHub today (Pushing, Pulling requests, Branches, etc) I'm just getting the hang of it.

Thanks for this amazing launcher and for letting me contribute.

**Comment by 0neGal** [comment]
> I literally learned to use GitHub today (Pushing, Pulling requests, Branches, etc) I'm just getting the hang of it.

The basis of PR's is you make a fork of a repo, your own version of you will, on it you make your changes, once they're made you can open a PR, which is you requests me to pull from your fork.

That is literally all it is, in Git terms updating and fetching new changes is called "pulling" hence the name, and furthermore in Git commands if i wanted to, instead of merging through the GitHub UI I could also just do `got pull https://github/<username>/<repo>` and it'll pull and merge it, resulting in the exact same thing as if if I clicked merge on GitHub.

Keep in mind Git != GitHub, it's much like saying Porn != PornHub, quite the same content, GitHub is a place to store Git repos, much like the other concept. And by extent I could pull from any URL and not just GitHub.

Git by itself can be complex but at a certain point it becomes more or less easy to understand, and even then you'll see people with years of experience struggle.

> Thanks for this amazing launcher and for letting me contribute.

And thank you for contributing, there's no barrier to entry here, if you have an internet connection you can help out, thats the beauty of open source software! :)

I hope you'll learn something along the way, and at the very least get on the Frontier and get a few kill streaks along the way!

**Pull request merged**
