### PR TITLE
feat: Option to close Origin when Viper exits

### PR DESCRIPTION
**Pull request by pcbmaster**
When I used to launch Northstar directly through Steam, I really liked how when I was finished, the Origin client would automatically be closed.  I don't use Origin for anything else, and I imagine there are others like me who would like this feature.  This PR adds a check for the Origin client process when exiting, and kills it if it's running.  Additionally I added the ability to turn this feature on or off in the settings, it defaults to off.  Hope this isn't too messy, Node/Electron is not what I do usually.

### CODE REVIEW

**Comment by 0neGal** [comment]
Generally this looks like it works, I haven't actually tested it, I'll have a few extra looks when I get the time to do so, likely within a few days, as I'm quite busy lately. One gripe I have with this PR is a lot of the syntax has been changed, not just on code you wrote, but on lines that weren't functionally changed, however the syntax was still change.

I have no clue if this is because of your editor auto-formatting things, I'll have a look at fixing that as well. There's a few other things I'd have to check and possibly change, but overall everything looks good.

**Comment by pcbmaster** [comment]
Oh yeah, looks like auto format mucked with a lot of whitespace, I didn't notice.  I'll fix that

**Comment by 0neGal** [comment]
I made a few changes to the localization, fixes and cleaned up very little code, so overall thanks for this PR. From my testing everything seems to work just fine, so when the localizations are added I'll be merging this.

@Alystrasz, @AA-Delta, strings to localize:
```json
"gui.settings.title.misc": "Miscellaneous",
"gui.settings.originkill.title": "Automatically quit Origin",
"gui.settings.originkill.desc": "When Viper exits, automatically quit Origin as well.",
```

**Comment by Alystrasz** [comment]
@0neGal I don't know how to propose a pull request into another pull request; you can cherry-pick French translations from there: aa9227e802e1075e650b3c02a938f8bc2c8bfce7

**Comment by 0neGal** [comment]
> @0neGal I don't know how to propose a pull request into another pull request, but you can cherry-pick French translations from there: [aa9227e](https://github.com/0neGal/viper/commit/aa9227e802e1075e650b3c02a938f8bc2c8bfce7)

Didn't quite consider that :p, I guess the only valid way to do that would be to make a PR on the original branch, but that's seems rather complicated. @AA-Delta, feel free to just drop the translations directly in here, or make a commit I can cherry pick, either will be fine.

**Comment by AA-Delta** [comment]
I'll leave here instead, don't want to mess up anything :p

```
"gui.settings.title.misc": "Misceláneos",
"gui.settings.originkill.title": "Cerrar Origin automáticamente",
"gui.settings.originkill.desc": "Cuando Viper se cierra, cerrar automáticamente Origin también.",
```

**Pull request merged**
